import * as path from 'node:path';
import { writeFileSafe, slugify } from '../utils.js';
import type { DossierResult, DossierFile } from '../core.js';

/* ------------------------------------------------------------------ */
/* Public types                                                        */
/* ------------------------------------------------------------------ */

export interface GenerateSiteOptions {
  /** Custom subdomain/host. When set, writes a public/CNAME file. */
  subdomain?: string;
  /**
   * Inject `<meta name="robots" content="noindex,nofollow">` on every page
   * and a Disallow-all robots.txt. Defaults to TRUE (unlisted by policy).
   */
  noindex?: boolean;
  /** Override the site title. Defaults to the dossier company name. */
  title?: string;
}

export interface GenerateSiteResult {
  /** Absolute path to the generated `site/` directory. */
  siteDir: string;
  /** Absolute paths of every file written, relative to nothing — fully qualified. */
  files: string[];
  /** Whether noindex/unlisted policy was applied. */
  noindex: boolean;
}

/* Pinned, recent versions (Node-only Astro Starlight). */
const ASTRO_VERSION = '^5.7.0';
const STARLIGHT_VERSION = '^0.34.0';
const GH_PAGES_VERSION = '^6.3.0';

const DISCLAIMER =
  'Auto-generated from public sources — may be inaccurate; not affiliated with the company.';
const TAKEDOWN =
  'Takedown / contact: open an issue at https://github.com/ever-just/company-dossier/issues';

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

/** Strip a leading YAML frontmatter block from generated markdown, if any. */
function stripFrontmatter(content: string): string {
  if (content.startsWith('---\n')) {
    const end = content.indexOf('\n---', 4);
    if (end !== -1) {
      const after = content.indexOf('\n', end + 1);
      return after !== -1 ? content.slice(after + 1) : '';
    }
  }
  return content;
}

/**
 * Extract a human title from a dossier markdown body.
 * Section files start with `# 1. Overview & Identity — Acme`; we keep the
 * descriptive part ("Overview & Identity") and drop the leading number and
 * the " — Company" suffix so the sidebar reads cleanly.
 */
function extractTitle(content: string, fallback: string): string {
  const m = content.match(/^#\s+(.+?)\s*$/m);
  if (!m) return fallback;
  let t = m[1].trim();
  t = t.replace(/^\d+\.\s*/, ''); // drop "1. "
  t = t.replace(/\s*[—–-]\s*[^—–-]+$/, ''); // drop " — Company"
  return t.trim() || fallback;
}

/** Derive a numeric order from a filename like "03_hiring_radar.md". */
function orderFromFilename(filePath: string): number | undefined {
  const m = path.basename(filePath).match(/^(\d+)/);
  return m ? parseInt(m[1], 10) : undefined;
}

/** Escape a value for safe single-line YAML (quote + escape quotes). */
function yamlString(value: string): string {
  return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function isOverview(filePath: string): boolean {
  const b = path.basename(filePath).toLowerCase();
  return b === 'readme.md' || /^0*1[_.]/.test(b) || b.includes('overview');
}

/* ------------------------------------------------------------------ */
/* Template builders                                                   */
/* ------------------------------------------------------------------ */

function buildPackageJson(name: string, deploy: boolean): string {
  const pkg: Record<string, unknown> = {
    name: `${slugify(name) || 'company'}-dossier-site`,
    private: true,
    version: '0.0.1',
    type: 'module',
    scripts: {
      dev: 'astro dev',
      build: 'astro build',
      preview: 'astro preview',
      ...(deploy ? { deploy: 'gh-pages -d dist -t true' } : {}),
    },
    dependencies: {
      astro: ASTRO_VERSION,
      '@astrojs/starlight': STARLIGHT_VERSION,
    },
    // gh-pages is an optional dep of the GENERATED site, not the main package.
    optionalDependencies: {
      'gh-pages': GH_PAGES_VERSION,
    },
  };
  return JSON.stringify(pkg, null, 2) + '\n';
}

function buildAstroConfig(title: string, noindex: boolean): string {
  const headEntry = noindex
    ? `
  head: [
    {
      tag: 'meta',
      attrs: { name: 'robots', content: 'noindex,nofollow' },
    },
  ],`
    : '';
  return `import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Generated by company-dossier (--format site).
// Per policy, per-company dossier sites are UNLISTED + NOINDEX by default.
export default defineConfig({
  integrations: [
    starlight({
      title: ${yamlString(title)},
      description: ${yamlString(DISCLAIMER)},
      tableOfContents: true,
      customCss: ['./src/styles/case-file.css'],${headEntry}
      // Sidebar autogenerated from the docs tree.
      sidebar: [
        {
          label: 'Dossier',
          autogenerate: { directory: '.' },
        },
      ],
      // Footer disclaimer + takedown line on every page.
      credits: false,
      lastUpdated: false,
      pagination: false,
    }),
  ],
});
`;
}

function buildContentConfig(): string {
  // LOOSE schema: extend Starlight's docs schema with optional extra keys so
  // generated frontmatter always validates. (A plain `.passthrough()` object
  // can't be intersected/merged with Starlight's hero schema, so we declare
  // tolerant optional fields instead — these cover the keys generated content
  // may carry now or later, and unknown-but-typed keys are accepted.)
  return `import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
import { z } from 'astro:content';

export const collections = {
  docs: defineCollection({
    loader: docsLoader(),
    schema: docsSchema({
      // Tolerant extra frontmatter keys for generated content.
      extend: z.object({
        order: z.number().optional(),
        section: z.string().optional(),
        sourceFile: z.string().optional(),
        generatedAt: z.string().optional(),
        company: z.string().optional(),
        domain: z.string().optional(),
        customNote: z.string().optional(),
      }),
    }),
  }),
};
`;
}

function buildCaseFileCss(): string {
  // "Case file" look: ink-on-paper light scheme via Starlight --sl-* props.
  return `/* company-dossier "case file" theme.
   Ink-on-paper light scheme expressed through Starlight design tokens. */

:root {
  /* Manila / paper accent (amber-brown ink stamp). */
  --sl-color-accent-low: #efe6d2;
  --sl-color-accent: #8a5a1f;
  --sl-color-accent-high: #4d3210;

  /* Ink on aged paper. */
  --sl-color-white: #1c1a16;
  --sl-color-gray-1: #2a2620;
  --sl-color-gray-2: #423c31;
  --sl-color-gray-3: #6b6253;
  --sl-color-gray-4: #8c8270;
  --sl-color-gray-5: #b9ad95;
  --sl-color-gray-6: #e6dcc6;
  --sl-color-gray-7: #f1e9d6;
  --sl-color-black: #faf4e4;

  --sl-color-bg: #faf4e4;
  --sl-color-bg-nav: #f1e9d6;
  --sl-color-bg-sidebar: #f4ecda;
  --sl-color-text: #1c1a16;
  --sl-color-text-accent: #8a5a1f;
  --sl-color-hairline: #d8cbac;
  --sl-color-hairline-light: #e6dcc6;

  --sl-font: ui-serif, Georgia, 'Times New Roman', serif;
  --sl-font-mono: ui-monospace, 'SFMono-Regular', 'Courier New', monospace;
}

/* Keep a dark variant readable too (folder-at-night). */
:root[data-theme='dark'] {
  --sl-color-accent-low: #2a2012;
  --sl-color-accent: #d9a441;
  --sl-color-accent-high: #f3d79a;
  --sl-color-bg: #16140f;
  --sl-color-bg-nav: #1d1a13;
  --sl-color-bg-sidebar: #1b1812;
  --sl-color-text: #ece2cc;
  --sl-color-hairline: #36301f;
}

/* Markdown content reads like a typed report. */
.sl-markdown-content {
  line-height: 1.6;
}
.sl-markdown-content table {
  font-family: var(--sl-font-mono);
  font-size: 0.85rem;
}

/* CONFIDENTIAL / disclaimer banner injected at the top of every page. */
.dossier-banner {
  border: 1px dashed var(--sl-color-accent);
  background: var(--sl-color-accent-low);
  color: var(--sl-color-accent-high);
  padding: 0.6rem 0.9rem;
  margin: 0 0 1.25rem 0;
  border-radius: 4px;
  font-family: var(--sl-font-mono);
  font-size: 0.8rem;
  line-height: 1.45;
}
.dossier-banner strong {
  display: inline-block;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  margin-right: 0.5rem;
}
.dossier-banner .dossier-takedown {
  display: block;
  margin-top: 0.35rem;
  opacity: 0.85;
}
`;
}

function buildRobotsTxt(noindex: boolean): string {
  if (noindex) {
    return 'User-agent: *\nDisallow: /\n';
  }
  return 'User-agent: *\nAllow: /\n';
}

/** Markdown disclaimer banner embedded in every generated doc. */
function disclaimerMarkdown(): string {
  return `:::caution[Disclaimer]
**CONFIDENTIAL — UNVERIFIED.** ${DISCLAIMER}

${TAKEDOWN}
:::

`;
}

/** Build the index.md (hero + overview) from the dossier overview/README. */
function buildIndexDoc(result: DossierResult, files: DossierFile[], title: string): string {
  const overviewFile =
    files.find((f) => path.basename(f.path).toLowerCase() === 'readme.md') ||
    files.find((f) => isOverview(f.path));
  const body = overviewFile ? stripFrontmatter(overviewFile.content) : '';
  // Drop the first top-level heading; the hero supplies the title.
  const bodyNoH1 = body.replace(/^#\s+.+?\r?\n/, '');

  const frontmatter = [
    '---',
    `title: ${yamlString(title)}`,
    'template: splash',
    'hero:',
    `  title: ${yamlString(title)}`,
    `  tagline: ${yamlString('Intelligence dossier compiled from public sources.')}`,
    '  actions:',
    `    - text: Read the dossier`,
    `      link: ./overview-identity/`,
    `      icon: right-arrow`,
    '---',
    '',
  ].join('\n');

  return frontmatter + disclaimerMarkdown() + bodyNoH1.trim() + '\n';
}

/** Build one Starlight doc from a dossier section file. */
function buildSectionDoc(file: DossierFile, title: string, order: number | undefined): string {
  const body = stripFrontmatter(file.content).replace(/^#\s+.+?\r?\n/, '');
  const fm: string[] = ['---', `title: ${yamlString(title)}`];
  if (order !== undefined) {
    fm.push('sidebar:', `  order: ${order}`);
  }
  fm.push('---', '');
  return fm.join('\n') + disclaimerMarkdown() + body.trim() + '\n';
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

/**
 * Turn a generated dossier into a themed, static Astro Starlight docs site.
 *
 * Scaffolds an Astro Starlight project under `<outDir>/site/`. Per policy,
 * the site is UNLISTED + NOINDEX by default: every page carries a
 * `noindex,nofollow` robots meta, a visible disclaimer, and a takedown line,
 * and robots.txt disallows all crawling.
 *
 * Build it with `cd site && npm install && npm run build` (output in
 * `site/dist`). Deploy is pluggable; pass a subdomain to emit a CNAME.
 */
export async function generateSite(
  result: DossierResult,
  outDir: string,
  opts: GenerateSiteOptions = {}
): Promise<GenerateSiteResult> {
  const noindex = opts.noindex !== false; // default true
  const title = (opts.title || result.meta.companyName || 'Company Dossier').trim();
  const siteDir = path.join(outDir, 'site');

  const written: string[] = [];
  const write = (rel: string, content: string) => {
    const abs = path.join(siteDir, rel);
    writeFileSafe(abs, content);
    written.push(abs);
  };

  const files = result.files;

  // Scaffold project files.
  write('package.json', buildPackageJson(title, true));
  write('astro.config.mjs', buildAstroConfig(title, noindex));
  write('src/content/config.ts', buildContentConfig());
  write('src/styles/case-file.css', buildCaseFileCss());
  write('tsconfig.json', JSON.stringify({ extends: 'astro/tsconfigs/strict' }, null, 2) + '\n');

  // Docs: index (from overview/README) + one per section.
  write('src/content/docs/index.md', buildIndexDoc(result, files, title));

  const usedSlugs = new Set<string>(['index']);
  for (const file of files) {
    const base = path.basename(file.path).toLowerCase();
    if (base === 'dossier.json') continue; // not a doc
    if (base === 'readme.md') continue; // folded into index
    if (!base.endsWith('.md')) continue;

    const docTitle = extractTitle(file.content, path.basename(file.path, '.md'));
    let slug = slugify(docTitle).replace(/_/g, '-') || slugify(base.replace(/\.md$/, ''));
    // Disambiguate collisions.
    let unique = slug;
    let n = 2;
    while (usedSlugs.has(unique)) unique = `${slug}-${n++}`;
    usedSlugs.add(unique);

    const order = orderFromFilename(file.path);
    write(`src/content/docs/${unique}.md`, buildSectionDoc(file, docTitle, order));
  }

  // Public assets.
  write('public/.nojekyll', '');
  write('public/robots.txt', buildRobotsTxt(noindex));
  if (opts.subdomain && opts.subdomain.trim()) {
    write('public/CNAME', opts.subdomain.trim() + '\n');
  }

  return { siteDir, files: written, noindex };
}
